# Legacy Docker Compose file for older versions (1.x)
# Use this if you have Docker Compose 1.x

db:
  image: mysql:8.0
  container_name: wificount-mysql
  restart: unless-stopped
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wificnt
    MYSQL_USER: wificount
    MYSQL_PASSWORD: wificount123
  ports:
    - "3307:3306"
  volumes:
    - /var/lib/mysql
    - ./backup_wepper.sql:/docker-entrypoint-initdb.d/init.sql
  command: --default-authentication-plugin=mysql_native_password

app:
  build: .
  container_name: wificount-app
  restart: unless-stopped
  ports:
    - "3000:3000"
  environment:
    - NODE_ENV=production
    - DATABASE_URL=mysql://wificount:wificount123@db:3306/wificnt
    - NEXTAUTH_URL=http://localhost:3000
    - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
    - NEXT_PUBLIC_API_URL=https://cnradiusapi.chilinet.cloud
    - NEXT_PUBLIC_API_KEY=zk4SNSo3dDJfKYdt7LdhG44BBEiGBjPE
  volumes:
    - ./uploads:/app/uploads
  links:
    - db

# Volumes are handled automatically in Docker Compose 1.x
