# Docker Compose file for Server with external MySQL
# This connects to an existing MySQL server on the host

app:
  build: .
  container_name: wificount-app
  ports:
    - "3000:3000"
  environment:
    - NODE_ENV=production
    - DATABASE_URL=mysql://wificount:wificount123@host.docker.internal:3306/wificnt
    - NEXTAUTH_URL=http://localhost:3000
    - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
    - NEXT_PUBLIC_API_URL=https://cnradiusapi.chilinet.cloud
    - NEXT_PUBLIC_API_KEY=zk4SNSo3dDJfKYdt7LdhG44BBEiGBjPE
  volumes:
    - ./uploads:/app/uploads
  network_mode: host
