# Simple Docker Compose file for Docker Compose 1.x
# This format is guaranteed to work with older versions

app:
  build: .
  container_name: wificount-app
  ports:
    - "3000:3000"
  environment:
    - NODE_ENV=production
    - DATABASE_URL=mysql://root:root@host.docker.internal:8889/wificnt
    - NEXTAUTH_URL=http://localhost:3000
    - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
    - NEXT_PUBLIC_API_URL=https://cnradiusapi.chilinet.cloud
    - NEXT_PUBLIC_API_KEY=zk4SNSo3dDJfKYdt7LdhG44BBEiGBjPE
  volumes:
    - ./uploads:/app/uploads
